<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.example.app</groupId>
    <artifactId>java-by-examples-25</artifactId>
    <packaging>pom</packaging>
    <version>1.0-SNAPSHOT</version>
    <name>java-by-examples-25</name>
    <url>http://maven.apache.org</url>
    <modules>
        <module>object-example</module>
        <module>method-example</module>
        <module>constructor-example</module>
        <module>interfaces-example</module>
        <module>abstract-classes</module>
        <module>design-pattern</module>
        <module>inheritance-example</module>
        <module>exception-handling-example</module>

    </modules>
</project>
