spring.application.name=springboot-crud-using-collections
spring.datasource.url=jdbc:mysql://localhost:3306/employeeDatabase?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=subhasmita
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
logging.level.org.springframework.boot.autoconfigure=DEBUG
